# Generated by Django 5.1.5 on 2025-02-05 14:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userincome',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
